"""desktop sessions

Revision ID: ee3c7b3e7908
Revises: 8c4e6cc27bfe
Create Date: 2026-09-29 12:59:24.467017

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ee3c7b3e7908'
down_revision: str | Sequence[str] | None = '8c4e6cc27bfe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('client', sa.String(length=16), nullable=False, server_default='web'))
    op.add_column('sessions', sa.Column('device_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'device_name')
    op.drop_column('sessions', 'client')
    # ### end Alembic commands ###
