from pathlib import Path
from typing import Protocol

from .domain import RemoteObject


class BucketStore(Protocol):
    async def put(self, key: str, source: Path) -> RemoteObject: ...

    async def get(self, key: str, destination: Path) -> Path: ...

    async def list(self, prefix: str = "") -> list[RemoteObject]: ...

    async def delete(self, key: str) -> None: ...

    async def exists(self, key: str) -> bool: ...

    async def presign_put(
        self, key: str, content_type: str, expires_in: int
    ) -> str: ...

    async def aclose(self) -> None: ...
